<section id="header">
        <header>
            <img id="logo" src="images/doki_logo.png" alt="A cat who sells ice cream"> 
            <h2>Little Doctor: Doki the Cat</h2>
        </header>
        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="fav_form.html">Survey</a></li>
                <li><a href="friends.html">Crew</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
        </nav>
    </section>